game_workspace/game/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "home#base"

  resources :games,  only: [:index]

end

game_workspace/game/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

game_workspace/game/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

game_workspace/game/app/controllers/games_controller.rb
class GamesController < ApplicationController

  def index
    @tmp_arr = ["Kayu", "Jamu", "Susu" , "Roti"]

    if params[:game].present?
      @check = params[:game][:tebak] == params[:game][:key].downcase
      if @check
        flash[:notice] = "Tebakanmu Benar"
      else
        flash[:notice] = "Tebakanmu Salah"
      end
    end

  end

end

game_workspace/game/app/controllers/home_controller.rb
class HomeController < ApplicationController

  def base
  end

end


# if @contact_form.deliver
#   flash[:notice] = "You message has been successfully sent. We will contact you very soon!"
#   redirect_to root_path
# end

game_workspace/game/app/helpers/application_helper.rb
module ApplicationHelper
end

game_workspace/game/app/views/games/index.html.haml
- select_value = @tmp_arr.sample
- value = select_value.gsub(/./){|s| s.send(%i[upcase downcase].sample)}

%p
  Tebak:
  = value
%p
  Jawab:
= simple_form_for :game, url: games_path, method: :get do |f|
  = f.input :tebak
  = f.hidden_field :key, value: "#{select_value}"
  = f.button :submit, "submit"

- if flash[:notice]
  = flash[:notice]

game_workspace/game/app/views/home/base.html.haml
= link_to "GAME TEBAK KATA" , games_path

game_workspace/game/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Game</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>